### ISSUE TITLE
关于tensor_type这个包是您自己写的还是公开包？请问在哪儿下载啊，有的话请告诉我，谢谢！

### ISSUE THREAD

**Issue by xiongchuanchao** [yangpuPKU/Self2Self_pytorch_implementation#1]

**Comment by yangpuPKU** [comment]
您可能指的是network/pconv.py中的代码，事实上这是公开包torch-pconv的源代码，具体可见https://pypi.org/project/torch-pconv/。您可以直接安装torch-pconv，亦或是使用
_pip install tensor_type_
仅安装tensor_type。
希望对您有帮助

**Comment by yangpuPKU** [comment]
您可能指的是network/pconv.py中的代码，事实上这是公开包torch-pconv的源代码，具体可见[https://pypi.org/project/torch-pconv/](https://pypi.org/project/torch-pconv/%E3%80%82%E6%82%A8%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E5%AE%89%E8%A3%85torch-pconv%EF%BC%8C%E4%BA%A6%E6%88%96%E6%98%AF%E4%BD%BF%E7%94%A8)。您可以直接安装torch-pconv，亦或是使用
_pip install tensor_type_
仅安装tensor_type。
希望对您有帮助^_^

**Comment by xiongchuanchao** [comment]
好的，感谢！

**Comment by xiongchuanchao** [comment]
> 您可能指的是network/pconv.py中的代码，事实上这是公开包torch-pconv的源代码，具体可见[https://pypi.org/project/torch-pconv/](https://pypi.org/project/torch-pconv/%E3%80%82%E6%82%A8%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E5%AE%89%E8%A3%85torch-pconv%EF%BC%8C%E4%BA%A6%E6%88%96%E6%98%AF%E4%BD%BF%E7%94%A8)。您可以直接安装torch-pconv，亦或是使用 _pip install tensor_type_ 仅安装tensor_type。 希望对您有帮助^_^

好的，谢谢。我发现代码里面没有学习率的调整，这个方法就是不需要调整学习率吗？

**Comment by yangpuPKU** [comment]
> > 您可能指的是network/pconv.py中的代码，事实上这是公开包torch-pconv的源代码，具体可见[https://pypi.org/project/torch-pconv/](https://pypi.org/project/torch-pconv/%E3%80%82%E6%82%A8%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E5%AE%89%E8%A3%85torch-pconv%EF%BC%8C%E4%BA%A6%E6%88%96%E6%98%AF%E4%BD%BF%E7%94%A8)。您可以直接安装torch-pconv，亦或是使用 _pip install tensor_type_ 仅安装tensor_type。 希望对您有帮助^_^
> 
> 好的，谢谢。我发现代码里面没有学习率的调整，这个方法就是不需要调整学习率吗？

有学习率的调整。参考https://github.com/yangpuPKU/Self2Self_pytorch_implementation/blob/main/main.py#L127。
希望对您有帮助^_^
