### ISSUE TITLE
同学您好，请问我用论文那张飞机图片训练出来的模型，然后我随便找张图片进行去噪，能够去噪声，但是图片的颜色变了这是为什么呢，麻烦你了

### ISSUE THREAD

**Issue by Cat-Guijun** [yangpuPKU/Self2Self_pytorch_implementation#3]
![image](https://github.com/yangpuPKU/Self2Self_pytorch_implementation/assets/70092901/f507f5a4-c2a0-4e93-8a56-75ee95859010)
![image](https://github.com/yangpuPKU/Self2Self_pytorch_implementation/assets/70092901/34f35e04-d7ed-4f14-a3be-54dd2c94831b)

**Comment by Cat-Guijun** [comment]
是遇到一张新图片就得重新训练一次吗，那这样模型岂不是没有啥泛化能力，我知识浅薄，问题比较肤浅，麻烦友友了

**Comment by yangpuPKU** [comment]
Yes, retraining is required for each new image.

**Comment by Cat-Guijun** [comment]
> Yes, retraining is required for each new image.

谢谢同学，同时感谢你提供的优质开源代码，谢谢。祝工作学习顺利
