### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by wam730** [yangpuPKU/Self2Self_pytorch_implementation#4]
你好，我想知道运行你们的代码的环境配置，以更好的复现，谢谢！

**Comment by yangpuPKU** [comment]
@wam730 很早之前的工作了，具体的版本我忘记了。不过应该没有用到会因为版本更替出现问题的语法，你可以尝试直接安装默认版本。主要的环境是：
python, numpy, torch, skimage, cv2. 
抱歉没有直接回答你的问题，希望对你有帮助！

**Comment by yangpuPKU** [comment]
@wam730 还有tensor_type

**Comment by wam730** [comment]
感谢解答！确实没有用到会由于版本更替而出现问题的代码，已经成功复现
